// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: social_network/social_network.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid.UUID в байтах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_social_network_social_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_network_social_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_social_network_social_network_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_social_network_social_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_network_social_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_social_network_social_network_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileRequest) Reset() {
	*x = UserProfileRequest{}
	mi := &file_social_network_social_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileRequest) ProtoMessage() {}

func (x *UserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_network_social_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileRequest.ProtoReflect.Descriptor instead.
func (*UserProfileRequest) Descriptor() ([]byte, []int) {
	return file_social_network_social_network_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfileRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type UserProfileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePhotoUrl string                 `protobuf:"bytes,4,opt,name=profile_photo_url,json=profilePhotoUrl,proto3" json:"profile_photo_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_social_network_social_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_network_social_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_social_network_social_network_proto_rawDescGZIP(), []int{3}
}

func (x *UserProfileResponse) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UserProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfileResponse) GetProfilePhotoUrl() string {
	if x != nil {
		return x.ProfilePhotoUrl
	}
	return ""
}

var File_social_network_social_network_proto protoreflect.FileDescriptor

const file_social_network_social_network_proto_rawDesc = "" +
	"\n" +
	"#social_network/social_network.proto\x12\x15api.social_network.v2\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"4\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"-\n" +
	"\x12UserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\"\x8a\x01\n" +
	"\x13UserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\x11profile_photo_url\x18\x04 \x01(\tR\x0fprofilePhotoUrl2a\n" +
	"\vUserService\x12R\n" +
	"\aGetUser\x12\".api.social_network.v2.UserRequest\x1a#.api.social_network.v2.UserResponse2y\n" +
	"\x0eProfileService\x12g\n" +
	"\x0eGetUserProfile\x12).api.social_network.v2.UserProfileRequest\x1a*.api.social_network.v2.UserProfileResponseB\x06Z\x04.;v2b\x06proto3"

var (
	file_social_network_social_network_proto_rawDescOnce sync.Once
	file_social_network_social_network_proto_rawDescData []byte
)

func file_social_network_social_network_proto_rawDescGZIP() []byte {
	file_social_network_social_network_proto_rawDescOnce.Do(func() {
		file_social_network_social_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_network_social_network_proto_rawDesc), len(file_social_network_social_network_proto_rawDesc)))
	})
	return file_social_network_social_network_proto_rawDescData
}

var file_social_network_social_network_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_social_network_social_network_proto_goTypes = []any{
	(*UserRequest)(nil),         // 0: api.social_network.v2.UserRequest
	(*UserResponse)(nil),        // 1: api.social_network.v2.UserResponse
	(*UserProfileRequest)(nil),  // 2: api.social_network.v2.UserProfileRequest
	(*UserProfileResponse)(nil), // 3: api.social_network.v2.UserProfileResponse
}
var file_social_network_social_network_proto_depIdxs = []int32{
	0, // 0: api.social_network.v2.UserService.GetUser:input_type -> api.social_network.v2.UserRequest
	2, // 1: api.social_network.v2.ProfileService.GetUserProfile:input_type -> api.social_network.v2.UserProfileRequest
	1, // 2: api.social_network.v2.UserService.GetUser:output_type -> api.social_network.v2.UserResponse
	3, // 3: api.social_network.v2.ProfileService.GetUserProfile:output_type -> api.social_network.v2.UserProfileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_network_social_network_proto_init() }
func file_social_network_social_network_proto_init() {
	if File_social_network_social_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_network_social_network_proto_rawDesc), len(file_social_network_social_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_social_network_social_network_proto_goTypes,
		DependencyIndexes: file_social_network_social_network_proto_depIdxs,
		MessageInfos:      file_social_network_social_network_proto_msgTypes,
	}.Build()
	File_social_network_social_network_proto = out.File
	file_social_network_social_network_proto_goTypes = nil
	file_social_network_social_network_proto_depIdxs = nil
}
